newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Elevate-Lab heartlyğŸ˜ƒ welcomes you to the project!ğŸ’–
  
  <img src="https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif" width="60" height="60" />
  
  Thank you and congratsğŸ‰for opening your very first issue in this project.Hope you have a great time there!ğŸ˜„ 
  
  You may submit a PR if you like! If you want to report a bugğŸ 
  please follow our [Issue Template](https://github.com/Elevate-Lab/Import-Template/tree/main/.github/ISSUE_TEMPLATE). 
  Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Elevate-Lab heartlyğŸ˜ƒ welcomes you to the project!ğŸ’–
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨.We will get back to you as soon as we can.ğŸ˜„

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
